version: "3.7"

services:
  database:
    image: postgres
    container_name: database_migoc2-teste
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=segredo
      - POSTGRES_DB=migoc2
    volumes:
      - pgdata:/data/postgres
    networks:
      - develop-net

volumes:
  pgdata:
    driver: local

networks:
  develop-net:
    driver: bridge
